### ISSUE TITLE
APIDefinitions missing RTCCameraVideoCapturer's constructor with IVideoSource as parameter in iOS

### ISSUE THREAD

**Issue by abhcr** [Onotseike/Xamarin-WebRTC-Tutorial#2]
How do I get a RTCCameraVideoCapturer's constructor with a IVideoSource/NativeObject parameter (in iOS)? I can't see anything like that in the current APIDefinitions.cs.

**Comment by Onotseike** [comment]
From the iOS Binding code: the only constructor accepts only an IRTCVideoCapturerDelgate, why do you want to have a constructor with IVideoSource for iOS?

`[Export("initWithDelegate:")]
  IntPtr Constructor(IRTCVideoCapturerDelegate @delegate);`

**Comment by Onotseike** [comment]
From the iOS Binding code: the only constructor accepts only an IRTC

`[Export("initWithDelegate:")]
        IntPtr Constructor(IRTCVideoCapturerDelegate @delegate);`

**Comment by abhcr** [comment]
How would I pass the video source to the RTCCameraVideoCapturer constructor while creating camera capturer in PeerConnection factory ? I tried  -> 

public ICameraVideoCapturer CreateCameraCapturer(IVideoSource videoSource, bool frontCamera)
        {
            var capturer = (RTCCameraVideoCapturer)new RTCVideoCapturer(videoSource.ToNative<RTCVideoSource>()); 
            return new CameraVideoCapturerNative(capturer, frontCamera);
        }
But this gives me "Error CS1503: Argument 1: cannot convert from 'WebRTC.iOS.Bindings.RTCVideoSource' to 'WebRTC.iOS.Bindings.RTCVideoCapturerDelegate' (CS1503)". I may be doing something totally wrong here.

**Comment by abhcr** [comment]
```
public ICameraVideoCapturer CreateCameraCapturer(IVideoSource videoSource, bool frontCamera)
 {
            var capturer = new RTCCameraVideoCapturer();
            capturer.WeakDelegate = videoSource.ToNative<RTCVideoSource>();
            return new CameraVideoCapturerNative(capturer, frontCamera);
}
```
Did the above (used weak delegate) instead of using the strongly typed Delegate or the initWithDelegate

**Comment by Onotseike** [comment]
> ```
> public ICameraVideoCapturer CreateCameraCapturer(IVideoSource videoSource, bool frontCamera)
>  {
>             var capturer = new RTCCameraVideoCapturer();
>             capturer.WeakDelegate = videoSource.ToNative<RTCVideoSource>();
>             return new CameraVideoCapturerNative(capturer, frontCamera);
> }
> ```
> 
> Did the above (used weak delegate) instead of using the strongly typed Delegate or the initWithDelegate

Oh... Your question was referencing how to use it in the context of the End Xamarin Forms iOS app. your work around works.
