### ISSUE TITLE
DemoApp.Android and .iOS needs migration

### ISSUE THREAD

**Issue by JoeyIreland** [Onotseike/Xamarin-WebRTC-Tutorial#3]
Hey,

when I open up the demo app .sln it says that the WebRTC.DemoApp.Android and WebRTC.DemoApp.iOS (needs migration).

I am on the latest version of Visual Studio do you know how to fix this as I really want to use this demo

**Comment by JoeyIreland** [comment]
Sorry,

you can close this, I was missing some installs on my VS Installer

**Comment by Onotseike** [comment]
> Hey,
> 
> when I open up the demo app .sln it says that the WebRTC.DemoApp.Android and WebRTC.DemoApp.iOS (needs migration).
> 
> I am on the latest version of Visual Studio do you know how to fix this as I really want to use this demo

Hi @JoeyIreland , I migrated the the Android project to AndroidX.

**Comment by Onotseike** [comment]
Okay
