### ISSUE TITLE
throw new RuntimeException("eglChooseConfig failed: 0x" + Integer.ToHexString(EGL14.EglGetError()));

### ISSUE THREAD

**Issue by Adeel984** [Onotseike/Xamarin-WebRTC-Tutorial#6]
Dear @Onotseike First of all i would like to thanks for your great contribution to Xamarin community. 
I'm running your code to Android but having following error on **WebRTC.Unified.Android** -> **EglBaseHelper** -> GetEglConfig(EGLDisplay eglDisplay, int[] configAttributes)

```
if (!EGL14.EglChooseConfig(eglDisplay, configAttributes, 0, configs, 0, configs.Length, numConfigs, 0))
                {
                    throw new RuntimeException("eglChooseConfig failed: 0x" + Integer.ToHexString(EGL14.EglGetError()));
                }

```
My code is going in if block could you please help me to get rid of this error. Thanks in advance & stay safe!

**Comment by Onotseike** [comment]
Hi @Adeel984 hope you are doing well. From my understanding egl14 falls under opengl. And that if statement attempts to find RGBA of a specific HEXSTRING for example 8888. Try commenting out the line to see if it runs.

Aside from this, what version of andros are you running on and also is this on the emulator or on an actual device?

**Comment by Adeel984** [comment]
Dear @Onotseike Thanks for your prompt response. I tried on both (Emulator & Physical device) API 28 & 29 respectively.

**Comment by Adeel984** [comment]
I commented those lines but the app is still crashing. How can i fix this?

**Comment by Onotseike** [comment]
Hi @Adeel984 could you put some break points to check were it seems to be crashing because I can't seem to reproduce the error.

In the meantime please use the following repo: https://github.com/Onotseike/Xamarin.WebRTC.Libraries

These send to be more stable and the tutorial since I have been fiddling around with some parts 🙈

**Comment by Adeel984** [comment]
Hi @Onotseike I'm testing your libraries meanwhile could you please clear my confusion about **Unified Libraries** Which library should be used? **Xamarin.WebRtc.Unified** or **WebRtc.Unified** ?

**Comment by Onotseike** [comment]
Hi @Adeel984 Webrtc.xamarin.unified

**Comment by Adeel984** [comment]
Okay i used the same.

**Comment by Adeel984** [comment]
Hi @Onotseike I can confirm this issue isn't appearing in the repo. but unfortunately i can see the video but not the voice?

**Comment by Adeel984** [comment]
> https://github.com/Onotseike/Xamarin.WebRTC.Libraries

Hi @Onotseike I can confirm this issue isn't appearing in the repo. but unfortunately i can see the video but not the voice?

**Comment by Onotseike** [comment]
Is your microphone capabilities/permissions set?

**Comment by Adeel984** [comment]
Permissions was not set. Now it's working fine. Thanks. I have 2 more questions How can i make call encrypted? and I want just voice not video. How i can i make it? Thanks in advance.

**Comment by Onotseike** [comment]
@Adeel984 with regards to voice only according to webrtc docs I believe it would modified in the media constraints  object exchanged via the signalling server so audio would be true whilst video would be false.

With regards to your Encryption question I haven't acquired that knowledge yet. I am still reading through the available docs at my disposal 🙃.

**Comment by Adeel984** [comment]
Okay @Onotseike Thank you so much for your support.
